### PR TITLE
rs2664 review modification

### PR DESCRIPTION
**Pull request by rs2664**
Dear Professor the  review comments have been applied

### CODE REVIEW

**Review by bjones1 — CHANGES_REQUESTED** [review]

**Comment by rs2664** [comment]
Dear Professor
Hello
Thank you for your comments. I have done the changes. Does it need to make another pull request? I have pulled the changes after the modifications. Many thanks for your considerations.

All the Best,
Ramin Salahi
________________________________

**Review by bjones1 — CHANGES_REQUESTED** [review]
Move this to the directory `OnBoarding/rs2664` then I'll approve.

**Comment by rs2664** [comment]
The file is moved to the requested folder with another pull request.

**Comment by bjones1** [comment]
Please resubmit on this branch -- don't open a new pull request.

**Comment by rs2664** [comment]
Dear Professor
I have tried to make the changes, but please let me check it with you after the class, if it doesn't work yet.

All the Best,
Ramin Salehi
________________________________

**Comment by rs2664** [comment]
Thank you so much for your help and consideration.  I will be grateful to meet you after the class.

All the Best,
Ramin
________________________________

**Comment by rs2664** [comment]
The change is done and the extra file is deleted.

**Comment by bjones1** [comment]
Looks good!

**Comment by rs2664** [comment]
Thank you so much for your help and consideration dear Professor.

All the best
Ramin
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
