### PR TITLE
Assignment ItG

### PR DESCRIPTION
**Pull request by bab1337**
Code was adjusted based upon suggestions or suggestions were ignored.

### CODE REVIEW

**Review by bjones1 — CHANGES_REQUESTED** [review]

**Comment by bab1337** [comment]
Changes made as requested.

**Comment by bab1337** [comment]
Requesting further Review!

**Review by bjones1 — CHANGES_REQUESTED** [review]
Good progress. Move your files to `TheDescent/bab1337` and I'll approve.

**Comment by bab1337** [comment]
Files moved sir.

**Pull request merged**
